server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://localhost:8081
          predicates:
            - Path=/reserveProcessings/** 
        - id: result
          uri: http://localhost:8082
          predicates:
            - Path=/resultProcessings/** 
        - id: mypage
          uri: http://localhost:8083
          predicates:
            - Path= /myviews/**
        - id: reserveOK
          uri: http://localhost:8084
          predicates:
            - Path=/comfirmProcesings/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reserve
          uri: http://reserve:8080
          predicates:
            - Path=/reserveProcessings/** 
        - id: result
          uri: http://result:8080
          predicates:
            - Path=/resultProcessings/** 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /myviews/**
        - id: reserveOK
          uri: http://reserveOK:8080
          predicates:
            - Path=/comfirmProcesings/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
